# Aquí pongo el nombre del workflow
name: My first workflow with gitHub

# ------------------------------------------------
# Especifico el trigger para el workflow
on:
  push: 
    branches:
      - '*' # Cualquier Rama
# ------------------------------------------------
# Especifico los Jobs
jobs:
  build:
    runs-on: ubuntu-latest # ambente de linux donde correrá el job
# -----------Steps del Job anterior---------------
    # Se definen los pasos del job 
    steps:
      - name: checkout repositorio # Nombre del primer paso
        uses: actions/checkout@v2 # deja el código del repo en una maquina runner

      - name: Imprimir un saludo # Nombre del script bash a ejecutar
        run: |
          echo "Hola, esto es una prueba en gitHub" # Ejecución del script 

